services:
  - type: web
    name: self-ping-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: SELF_URL
        value: https://self-ping-api.onrender.com
